services:

  # angular frontend
  holopcAngular:
    container_name: holopc_angular
    image: holopc_angular:1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    
    depends_on:
      - holopcWhisper

  # python backend
  holopcWhisper:
    container_name: holopcWhisper
    image: holopc_whisper:1.0.0
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8765:8765
    